# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "resque-throttle"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott J. Tamosunas"]
  s.date = "2012-04-02"
  s.description = "resque-throttle is an extension to the resque queue system that restricts the frequency in which certain jobs are run. Add more description here."
  s.email = "tamosunas@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/resque-throttle.rb",
    "lib/resque/resque.rb",
    "lib/resque/throttle.rb",
    "lib/resque/throttled_job.rb",
    "resque-throttle.gemspec",
    "test/resque/resque_test.rb",
    "test/resque/throttled_job_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/scotttam/resque-throttle"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "resque-throttle is an extension to the resque queue system that restricts the frequency in which certain jobs are run."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 1.6.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<resque>, [">= 1.6.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<resque>, [">= 1.6.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end

